#!/usr/bin/python

import os
import shutil

def rm_test_dir():
	cwd = os.getcwd()
	for filename in os.listdir(cwd):
		if not (filename.endswith("_env") or filename.endswith("_script")):
			if os.path.isfile(filename):
				os.remove(filename)
			else:
				shutil.rmtree(filename)

if __name__=="__main__":
	rm_test_dir()
