#!/usr/bin/python

import os

def create_testdir():
	current_directory = os.getcwd()
	final_directory = os.path.join(current_directory, r'test_dir')
	if not os.path.exists(final_directory):
		os.makedirs(final_directory)

def create_testfiles():
	pass

if __name__=="__main__":
	create_testdir()
	create_testfiles()
