#!/bin/bash
#SBATCH --array=0-2
#SBATCH --partition=express
#
# Name your job to make it easier for you to track
#
#SBATCH --job-name=test_job_%A_%a
#
# Set your error and output files
#
#SBATCH --error=job_err/test_job_%A_%a.err
#SBATCH --output=job_out/test_job_%A_%a.out
#SBATCH --ntasks=1
#
# Tell the scheduler only need 10 minutes
#
#SBATCH --time=00:10:00
#SBATCH --mem-per-cpu=256
#
# Set your email address and request notification when you job is complete or if it fails
#
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=$USER@uab.edu
FLOWCELL=($(less test.txt | awk -F' ' '{print $1}'))
HAIB=($(less test.txt | awk -F' ' '{print $2}'))
SAMPLE=($(less test.txt | awk -F' ' '{print $3}'))
echo ${FLOWCELL[$SLURM_ARRAY_TASK_ID]}
echo ${HAIB[$SLURM_ARRAY_TASK_ID]}
echo ${SAMPLE[$SLURM_ARRAY_TASK_ID]}
