#!/bin/bash
#SBATCH --array=1-126
#SBATCH --partition=express
#
# Name your job to make it easier for you to track
#
#SBATCH --job-name=job_%A_%a
#
# Set your error and output files
#
#SBATCH --ntasks=1
#
# Tell the scheduler only need 10 minutes
#
#SBATCH --time=2:00:00
#SBATCH --mem-per-cpu=4G
#SBATCH --cpus-per-task=16
#
# Set your email address and request notification when you job is complete or if it fails
#
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=$USER@uab.edu
a="t.list"
b="t2.list"
firstParameter=$(sed "${SLURM_ARRAY_TASK_ID}q;d" $a)
secondParameter=$(sed "${SLURM_ARRAY_TASK_ID}q;d" $b)